### ISSUE TITLE
Text missing in some verses

### ISSUE THREAD

**Issue by mtgred** [HelloAOLab/bible-api#3]
Examples:

* In Genesis 26:9 `Isaac replied, “Because I thought I might die on account of her.”` is missing from https://bible.helloao.org/api/BSB/GEN/26.json
Reference: https://www.bible.com/bible/3034/GEN.26.BSB or https://bereanbible.com/bsb-book.pdf

* In Genesis 27:1 `“Here I am,” Esau replied.` is missing from https://bible.helloao.org/api/BSB/GEN/27.json
Reference: https://www.bible.com/bible/3034/GEN.27.BSB

An easy way to spot the missing text is the presence of 2 `{ "type": "line_break" }` in a row.

**Comment by KallynGowdy** [comment]
I should be able to look into this more Wednesday

**Comment by KallynGowdy** [comment]
This is fixed in [v1.2.0](https://github.com/HelloAOLab/bible-api/releases/tag/v1.2.0).
