### ISSUE TITLE
Please make translation id and book id case insensitive

### ISSUE THREAD

**Issue by mtgred** [HelloAOLab/bible-api#4]
Chrome changes the url case if it is present in the browser history with different cases.

For instance, if a user goes to http://localhost:5173/bsb/gen/26 and then http://localhost:5173/BSB/GEN/26, Chrome will convert the later to the former. 

See https://stackoverflow.com/a/57084047/265773

**Comment by KallynGowdy** [comment]
This is not possible with how the API is currently constructed. URLs are case sensitive, and the API is designed for clients that understand this and handle it correctly. Additionally, the API allows users to use either the book ID (e.g. `JOB`) or the common name (e.g. `Job`), and so making it case-insensitive would break this scenario by returning inconsistent results.

From what I understand, Chrome defaults to selecting the case-corrected version, but you can still select the other version by using the dropdown box: 
![image](https://github.com/user-attachments/assets/0a3f5733-b743-452d-b917-52174bf6cb1e)
