### ISSUE TITLE
Missing books for many translations

### ISSUE THREAD

**Issue by mtgred** [HelloAOLab/bible-api#5]
Example:
```
{
id: "fra_ncl",
name: "Sainte Bible néo-Crampon Libre",
website: "https://ebible.org/Scriptures/details.php?id=francl",
licenseUrl: "https://ebible.org/Scriptures/details.php?id=francl",
shortName: "NCL",
englishName: "NCL",
language: "fra",
textDirection: "ltr",
availableFormats: [
"json"
],
listOfBooksApiLink: "/api/fra_ncl/books.json"
}
```
https://bible.helloao.org/api/fra_ncl/GEN/26.json gives an 404 error

Genesis and many other books are missing from https://bible.helloao.org/api/fra_ncl/books.json

The issue happens for many other translations.

**Comment by KallynGowdy** [comment]
Many translations are in active development and use, and are therefore incomplete. `fra_ncl` is an example of this in that it was updated very recently (July 14, 2024 was the last update according to ebible) with greater coverage and those changes haven't made their way into our API yet.

**Comment by mtgred** [comment]
The Sainte Bible néo-Crampon Libre translation is seem to be complete since at least 2022.

You can read the Genesis 26 chapter on their website: https://ebible.org/study/?w1=bible&t1=local%3Afrancl&v1=JN1_1

In any case, is there a way to filter out translations that aren't complete?

**Comment by KallynGowdy** [comment]
On ebible.org, the [details page](https://ebible.org/Scriptures/details.php?id=francl) seems to indicate that it was last updated on July 14th, 2024. So while it has a copyright dating to 2022, it may not have been completed at that time. Additionally, there's no changelog for it so it is a little hard to track when changes were made (the [ebible.org changelog](https://ebible.org/Scriptures/changelog.txt) doesn't seem to note any updates for it.) So yeah, this area is just a little difficult to track with so many different translations and fairly little information on what gets updated and when.

And that is a good idea. I'll see if I have time to add something that can help with that. There currently isn't a way to filter from the translations endpoint, but it would be possible to filter from the books endpoint.
