### ISSUE TITLE
Not clear how to derive the language from the 3 letters code

### ISSUE THREAD

**Issue by mtgred** [HelloAOLab/bible-api#6]
The documentation for the translation endpoint says `language` is `The RFC 5646 letter language tag that the translation is primarily in.` https://bible.helloao.org/docs/reference/#code-example

The language code returned by https://bible.helloao.org/api/available_translations.json are 3 letters codes (eg. `"eng"`) which don't match the RFC 5646 tags (eg. `"en"` or `"en-GB"`) https://gist.github.com/msikma/8912e62ed866778ff8cd

It seems to be closer to ISO 639 tags (https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes). But many of the language codes returned by the translations endpoint are not in the ISO 639 list (eg. `"ikk"` or `"ixl"`)

**Comment by KallynGowdy** [comment]
Ah that is a documentation error. It should note that they are ISO 639-3 tags.

Also that list from Wikipedia doesn't list all 3 character language tags. I would recommend using the [ISO 639 code tables](https://iso639-3.sil.org/code_tables/639/data) for looking up information on a particular tag.

**Comment by mtgred** [comment]
Thanks for the clarification and the complete language code list.

Would it possible to add the language name to the translation endpoint?

**Comment by KallynGowdy** [comment]
This is fixed in [v1.2.0](https://github.com/HelloAOLab/bible-api/releases/tag/v1.2.0).
